# Generated by Django 3.1.4 on 2020-12-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='team')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('desg', models.CharField(blank=True, max_length=250)),
                ('qualification', models.CharField(blank=True, max_length=300)),
                ('doj', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
