# Generated by Django 3.1.4 on 2020-12-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201209_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='achievement'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='desg',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='doj',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='qualification',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
