# Generated by Django 3.1.4 on 2020-12-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201209_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='atl')),
                ('desc', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
