# Generated by Django 3.1.4 on 2020-12-12 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_showcase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactForm',
        ),
    ]
