# Generated by Django 3.1.4 on 2020-12-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201213_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.FileField(blank=True, null=True, upload_to='notice')),
            ],
        ),
    ]
