# Generated by Django 3.1.4 on 2020-12-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_notice_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('quantity', models.CharField(max_length=300)),
            ],
        ),
    ]
