# Generated by Django 3.1.4 on 2020-12-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_purchaseform'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseform',
            name='mobile',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='purchaseform',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
