# Generated by Django 3.1.4 on 2020-12-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201227_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('orderId', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('quantity', models.CharField(max_length=300)),
                ('mobile', models.CharField(default='', max_length=300)),
                ('name', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='PurchaseForm',
        ),
    ]
