# Generated by Django 3.1.4 on 2020-12-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20201227_1630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievement',
            new_name='Gallery',
        ),
    ]
