# Generated by Django 3.1.4 on 2020-12-27 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20201227_1707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atl',
            new_name='ATL_Lab_Picture',
        ),
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='General_Enquiry',
        ),
        migrations.RenameModel(
            old_name='Notice',
            new_name='Notice_Board',
        ),
    ]
