# Generated by Django 3.1.4 on 2021-02-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20201227_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_board',
            name='link',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
